// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzWalks.DATA;

#nullable disable

namespace NzWalks.Migrations
{
    [DbContext(typeof(NzWalksDbContext))]
    partial class NzWalksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NzWalks.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("NzWalks.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("WalkDifficultyID")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NzWalks.Models.Domain.WalkDifficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WalkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WalkId");

                    b.ToTable("WalkDifficulty");
                });

            modelBuilder.Entity("RegionWalk", b =>
                {
                    b.Property<Guid>("RegionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WalksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegionID", "WalksId");

                    b.HasIndex("WalksId");

                    b.ToTable("RegionWalk");
                });

            modelBuilder.Entity("NzWalks.Models.Domain.WalkDifficulty", b =>
                {
                    b.HasOne("NzWalks.Models.Domain.Walk", null)
                        .WithMany("WalkDifficulty")
                        .HasForeignKey("WalkId");
                });

            modelBuilder.Entity("RegionWalk", b =>
                {
                    b.HasOne("NzWalks.Models.Domain.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NzWalks.Models.Domain.Walk", null)
                        .WithMany()
                        .HasForeignKey("WalksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NzWalks.Models.Domain.Walk", b =>
                {
                    b.Navigation("WalkDifficulty");
                });
#pragma warning restore 612, 618

        }
    }
}
